# Generated by Django 4.1.1 on 2022-09-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('FIRST_NAME', models.CharField(max_length=50)),
                ('LAST_NAME', models.CharField(max_length=50)),
                ('EMAIL', models.EmailField(max_length=50)),
                ('NUMBER', models.CharField(max_length=50)),
                ('AGE', models.CharField(max_length=50)),
                ('GENDER', models.CharField(max_length=50)),
            ],
        ),
    ]
